{{- if .Values.testApp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-test-app
  namespace: argocd
  # Adding a finalizer ensures that if the root app is deleted, 
  # the child apps are also cleaned up properly.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/chrisblatt/homelab-gitops.git'
    targetRevision: 'HEAD'
    path: apps/test-app
    helm:
      {{- if .Values.testApp }}
      valuesObject:
        {{- omit .Values.testApp "enabled" | toYaml | nindent 10 }}
      {{- else }}
      valuesObject: {}
      {{- end }}        
  destination:
    # Use the cluster name/server passed from the ApplicationSet
    name: {{ .Values.clusterName }}
    namespace: test-app
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}