apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cluster-specific resources (ConfigMap for nginx index)
resources:
- configmap-patch.yaml

# Patches to apply to the helm-rendered Deployment
patches:
- target:
    kind: Deployment
    name: example-patch
  path: deployment-patch.yaml

namespace: example-patch

