{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-helm.fullname" . }}
  labels:
    randomKey: "{{ .Values.randomKey }}"
    {{- include "test-helm.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
